apiVersion: v1
kind: Pod
metadata:
  name: console
spec:
  restartPolicy: Always
  containers:
    - name: {{{.api.name}}}
      image: {{{.api.image}}}
  someaddresses:
    {{{range .api.ipaddressrange}}}
    - ip: {{{.}}}{{{end}}}
