---
language: go

os:
  - linux
  - osx

go:
  - "1.8"
  - "1.9"
  - "1.10"

install:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get -v ./...

script:
  - go vet -v ./...
  - go test -v -cover ./...
