---
language: go

env:
  - DEP_VERSION="0.4.1"
os:
  - linux

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - master

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - go vet -v $(go list ./... | grep -v /vendor/)
  - go test --cover -v ./...
